config/routes.rb
Rails.application.routes.draw do
  resources :rackets

  root 'rackets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/racket.rb
class Racket < ApplicationRecord

  enum brand: { Avalox:0, Butterfly:1, Donic:2, DoubleDay:3, DHS:4, Joola:5, Mizuno:6, 
                Nittaku:7, Stiga:8, TSP:9, Tibhar:10, Victas:11, Xiom:12, Yasaka:13 }
  enum code: { I:0, J:1, K:2, L:3, M:4, N:5, O:6, P:7, Q:8, R:9, S:10, T:11, U:12, V:13 }
  enum grip: { FL:0, ST:1, AN:3 }
  enum material: { '5 ply wood':0, '7 ply wood':1, ALC:2, ZLC:3, SuperZLC:4, InnerCarbon:5 }
  enum thickness: { '5.2':0, '5.3':1}
  
  validates :brand, presence: true
  validates :product, length: { in: 1..20 }, presence: true
  validates :grip, presence: true

  private
  def uppercase_grip
    grip.upcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rackets_controller.rb
class RacketsController < ApplicationController
  before_action :find_racket, only: [:edit, :update, :destroy]

  def index
    @rackets = Racket.page(params[:page]).per(5)
  end

  def new
    @racket = Racket.new
  end

  def create
    @racket = Racket.new(racket_params)

    if @racket.save
      redirect_to rackets_path,notice: "新增球拍成功！"
    else
      respond_to do |format|
        format.html {render :new}
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @racket.update(racket_params)
      redirect_to rackets_path,notice: "更新資料成功！"
    else
      render :edit
    end
  end

  def destroy
    @racket.destroy if @racket
    respond_to do |format|
      format.js
      redirect_to rackets_path, notice: "球拍資料刪除成功！"  
    end 
  end

  private
  
  def racket_params
    params.require(:racket).permit(:brand, :product, :code, :grip, :material, :weight, :size, :thickness)
  end

  def find_racket
    @racket = Racket.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_link_to(label, path, icon)
    link_to path do
      content_tag :span, class: "btn btn-sm btn-primary glyphicon glyphicon-#{icon}" do
        label  
      end
    end
  end

  def if_butterfly(event)
    
  end

end

app/helpers/rackets_helper.rb
module RacketsHelper
end

app/helpers/ttrackets_helper.rb
module TtracketsHelper
end

app/views/frontend/_flash.html.erb
<div class="alert alert-success" role="alert" >
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ttracket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'frontend/flash' if notice %>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/rackets/_create.js.erb
$( '.racket-model-form' ).html( "<%= escape_javascript( render 'rackets/form', racket: @racket ) %>" )
$("#user-modal-form").html("<%= escape_javascript(render 'users/form', user: @user) %>");

app/views/rackets/_destroy.js.erb
$( '.delete' ).bind( 'ajax.success', function() {
  $(this).closet( 'tr' ).fadeOut()
})

app/views/rackets/_form.html.erb
<% if @racket.errors.present? %>
  <ul>
    <% @racket.errors.each do |error, message| %>
      <li>
        <%= t("#{error} ") + t('rackets.validate.error') + " #{message}" %>
      </li>
    <% end %>
  </ul>
<% end %>


<%= simple_form_for(racket, html: { class:"racket-model-form" } ) do |racket| %>
  <div class="brand form-group">
    <%= racket.input :brand, label: "品牌" %>
  </div>

  <div class="form-group">
    <%= racket.input :product, label: "產品名稱" %>
  </div>

  <div class="code form-group">
    <%= racket.input :code, label: "編碼" %>
  </div>
  
  <div id="content">
  </div>

  <div class="form-group">
    <%= racket.input :grip, label: "握柄" %>
  </div>

  <div class="form-group">
    <%= racket.input :material, label: "結構" %>
  </div>
  
  <div class="form-group">
    <%= racket.input :weight, label: "拍重", placeholder: "請輸入空拍重量(g)" %>
  </div>
  
  <div class="form-group">
    <%= racket.input :size, label: "拍面大小", placeholder: "157*150" %>
  </div>

  <div class="form-group">
    <%= racket.input :thickness, label: "厚度" %>
  </div>
    <%= racket.submit %>

  <script>
  // $('#ajax-load').click(function(){
  //   $.ajax('hello.html.erb', {
  //     success: function(response) {
  //       $('#content').html(response).slideDown();
  //     }
  //   })
  // })
  $('#ajax-load').click(function(e){
    e.preventDefault()
    var url = $(this).attr("href")
    $.ajax(url,{
      success: function(response){
        $('#content').html(response)
      }
    })
  })

  </script>
    
<% end %>

app/views/rackets/edit.html.erb
<h1>編輯球拍資訊</h1>

<%= render "form", racket: @racket %>

<%= link_to "回首頁", rackets_path %>

app/views/rackets/hello.html.erb
<div class="ticket">
  <h1>hello!</h1>
</div>

app/views/rackets/index.html.erb
<h1>桌球拍收納庫</h1>

<%= link_to "<span class='glyphicon glyphicon-plus'></span>新增球拍".html_safe, new_racket_path, class: "btn btn-sm btn-primary"  %>

<table class="table" >
  <thead>
    <tr>
      <td>品牌</td>
      <td>產品名稱</td>
      <td>編碼</td>
      <td>握柄</td>
      <td>結構</td>
      <td>拍重</td>
      <td>拍面大小</td>
      <td>厚度</td>
    </tr>
  </thead>
  <tbody>
    <% @rackets.each do |racket| %>
    <tr>
      <td> <%= link_to "幫我貼皮", "#", class:" btn btn-sm btn-primary " %> </td>
      <td> <%= racket.brand %> </td>
      <td> <%= racket.product %> </td>
      <td> <%= racket.code %> </td>
      <td> <%= racket.grip %> </td>
      <td> <%= racket.material %> </td>
      <td> <%= racket.weight %>克</td>
      <td> <%= racket.size %> </td>
      <td> <%= racket.thickness %> </td>
      <td>
        <%= link_to "<span class='glyphicon glyphicon-pencil'></span>編輯".html_safe,
            edit_racket_path(racket), 
            class: "btn btn-sm btn-warning" %>
        <%= link_to "刪除", racket_path(racket), 
            method:"delete",
            data: { confirm:"確認刪除？" }, 
            remote: true, class: "delete" %>
      </td>
    </tr>
    
    <% end %>
  </tbody>
</table>

<div class="ver", style="text-align:center">
  <%= link_to "中文版",'#' %>
  <%= link_to "英文版",'#' %>
</div>
<%= paginate @rackets,window: 2, remote: true %>

app/views/rackets/new.html.erb
<h1>新增球拍收藏</h1>

<%= render "form", racket: @racket %>

<%= link_to "回首頁", rackets_path %>